name: Build Images

on:
  push:
    branches:
      - arch-miyubi
  watch:
    types: [started]
  schedule:
      # Start every 3 days
      - cron: "00 0 */3 * *"
  workflow_dispatch:

jobs:
  full:
    runs-on: ubuntu-22.04
    env:
      IMAGE_TAG: arch

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuring git
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_EMAIL
      - name: Logging in to Docker
        run: |
          echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Building the Image
        run: |
          docker build -t miyoubix/arch --target full .
          echo "Build Completed Successfully!"
      - name: Pushing the Image
        run: |
          docker push miyoubix/arch

  minimal:
    runs-on: ubuntu-22.04
    env:
      IMAGE_TAG: arch-minimal

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuring git
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_EMAIL
      - name: Logging in to Docker
        run: |
          echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Building the Image
        run: |
          docker build -t miyoubix/arch --target minimal .
          echo "Build Completed Successfully!"
      - name: Pushing the Image
        run: |
          docker push miyoubix/arch

  with-tc:
    runs-on: ubuntu-22.04
    needs: minimal
    env:
      IMAGE_TAG: arch-wtc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuring git
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_EMAIL
      - name: Logging in to Docker
        run: |
          echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Building the Image
        run: |
          docker build -t miyoubix/arch --target wtc .
          echo "Build Completed Successfully!"
      - name: Pushing the Image
        run: |
          docker push miyoubix/arch

  deprecated:
    runs-on: ubuntu-22.04
    needs: minimal
    env:
      IMAGE_TAG: arch-miyubi

    steps:
    - uses: actions/checkout@master
    - name: Push to dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: miyoubix/arch
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildoptions: "--compress --force-rm"